version: 2

models:
  - name: mart_airline_performance
    description: Monthly carrier scorecard
    columns:
      - name: flight_month
        tests: [not_null]
      - name: carrier_code
        tests: [not_null]

  - name: mart_airport_delays
    description: Monthly airport departure delay stats
    columns:
      - name: origin_airport_code
        tests: [not_null]

  - name: mart_delay_causes
    description: Monthly national delay cause breakdown
    columns:
      - name: flight_month
        tests: [not_null, unique]
