version: 2

models:
  - name: stg_flights
    description: Cleaned and typed BTS On-Time Performance flights
    columns:
      - name: flight_date
        tests: [not_null]
      - name: carrier_code
        tests: [not_null]
      - name: origin_airport_code
        tests: [not_null]
      - name: dest_airport_code
        tests: [not_null]
